
project_id = "sogpdmzdfshhrjtpyvox"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.app"]
jwt_expiry = 3600
enable_signup = true
email_double_confirm_changes = true
enable_manual_linking = false

[edge_functions]
enabled = true
port = 54323

[functions.ai-roadmap-analysis]
verify_jwt = true

[functions.ai-development-chat]
verify_jwt = true

[functions.ai-auto-generation]
verify_jwt = true

[db]
enabled = true
port = 54322
shadow_port = 54320
major_version = 15
