// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sogpdmzdfshhrjtpyvox.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvZ3BkbXpkZnNoaHJqdHB5dm94Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MTU5OTcsImV4cCI6MjA2NDA5MTk5N30.b7HFKvQUPmgvRFMwjmgknZ6msswmipFrNW4mY08hVhk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);